branch-defaults:
  dev:
    environment: flow2-dev
  master:
    environment: flow2
global:
  application_name: flow2
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: git
